function oaSearcher(){var x=jQuery.trim(jQuery('#searchInput').val());if(x!=''){window.open(jQuerysiteUrl+'?page=buscador&s='+encodeURI(x),'_self');}}
function shareIt(){jQuery('#velo').css({width:jQuery(window).width(),height:jQuery(document).height()}).show();var url=document.URL;var ref=(url.search(/ref=/i)!=-1)?'':'&ref=recom';url+=ref;jQuery('#oaIframe').attr('src','?type=iframe&action=share&url='+escape(url)).css({left:.5*(jQuery(window).width()-jQuery('#oaIframe').width()),top:jQuery(window).scrollTop()+150}).show();}
var menuTab={exdays:1,cookieName:'menuNav'}
menuTab.setCookie=function(c_value){var expires='';if(menuTab.exdays!=null){var date=new Date();date.setTime(date.getTime()+(menuTab.exdays*24*60*60*1000));expires='; expires='+date.toGMTString();}
document.cookie=menuTab.cookieName+'='+c_value+expires+'; path=/';}
menuTab.getCookie=function(c_name){var nameEQ=c_name+'=';var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length);}
return null;}
menuTab.checkCookie=function(){var cookieValue=menuTab.getCookie(menuTab.cookieName);var result=Array(false,'','');if(cookieValue!=null&&cookieValue!=''){result[0]=true;result[1]=cookieValue;}
return result;}
var oaFB={currentIndex:0,fadingTime:800,expositionTime:5000,timeout:null};function banner_footer(){var ULs=jQuery('#footerBannerContainer div.ul');ULs.eq(oaFB.currentIndex).fadeOut(oaFB.fadingTime,function(){oaFB.currentIndex+=1;if(oaFB.currentIndex>=ULs.length)
oaFB.currentIndex=0;ULs.eq(oaFB.currentIndex).fadeIn(oaFB.fadingTime);});oaFB.timeout=setTimeout('banner_footer()',oaFB.expositionTime);}
function banner_footerNeo(){var ULs=jQuery('.footerNeoContainer');ULs.eq(oaFB.currentIndex).fadeOut(oaFB.fadingTime,function(){oaFB.currentIndex+=1;if(oaFB.currentIndex>=ULs.length)
oaFB.currentIndex=0;ULs.eq(oaFB.currentIndex).fadeIn(oaFB.fadingTime);});oaFB.timeout=setTimeout('banner_footerNeo()',oaFB.expositionTime);}
jQuery(function(){if(jQuery.browser.msie){jQuery('.headerBullet').css('opacity',0);}
if(jQuery('#tabSelector li').length>0){jQuery('#tabSelector li').each(function(index){jQuery(this).click(function(){if(!jQuery(this).hasClass('tabSelected')){jQuery('#tabContentContainer div.contentTab').addClass('hidden');jQuery('#tabContentContainer div.contentTab').eq(index).removeClass('hidden');jQuery('#tabSelector li').removeClass('tabSelected');jQuery(this).addClass('tabSelected');}});});}
jQuery('.sidebarSwitcher').each(function(index){jQuery(this).click(function(){if(jQuery(this).hasClass('sidebarSwitcherOff')){var cookieValue=jQuery(this).attr('title');menuTab.setCookie(cookieValue);jQuery('.sidebarMenu').addClass('hidden');jQuery('.sidebarMenu').eq(index).removeClass('hidden');jQuery('.sidebarSwitcher').addClass('sidebarSwitcherOff');jQuery(this).removeClass('sidebarSwitcherOff');}});});jQuery('#sidebarMenu li a').hover(function(){jQuery(this).animate({left:'+=10px'},200);},function(){jQuery(this).animate({left:0},150);});jQuery('#header #headerMenu a').each(function(index){jQuery(this).hover(function(){var pos=jQuery(this).offset();jQuery('.headerBullet').eq(index).css({left:pos.left-30,top:pos.top+5,opacity:0}).animate({left:'+=20px',opacity:1},250);},function(){jQuery('.headerBullet').eq(index).animate({left:'-=20px',opacity:0},250);});});jQuery('.searcherBtn').click(function(){oaSearcher();});jQuery('#searchInput').keypress(function(e){if(e.keyCode=='13')
oaSearcher();});});jQuery(window).load(function(){banner_footer();banner_footerNeo();});